### ISSUE TITLE
KeyError of step 3

### ISSUE THREAD

**Issue by ChenJin2020** [YangLabHKUST/SpatialScope#6]
Hi,

Thanks for the nice tool. I encountered a key error when running the step 3 with the demo data (10x Visium human heart data). Here is the error:

python ./src/Decomposition.py --tissue heart --out_dir  ./output --SC_Data ./Ckpts_scRefs/Heart_D2/Ref_Heart_sanger_D2.h5ad --cell_class_column cell_type  --ckpt_path ./Ckpts_scRefs/Heart_D2/model_5000.pt --spot_range 0,100 --gpu 0,1,2,3

2024-01-18 17:20:57,374 : INFO : load scRNA-seq reference: ./Ckpts_scRefs/Heart_D2/Ref_Heart_sanger_D2.h5ad
2024-01-18 17:20:58,700 : INFO : scRNA-seq reference data shape: (17369, 2195)
2024-01-18 17:20:58,700 : INFO : scRNA-seq reference cell class number: 10
2024-01-18 17:20:58,799 : INFO : load checkpoint: ./Ckpts_scRefs/Heart_D2/model_5000.pt
Traceback (most recent call last):
  File "/SpatialScope/./src/Decomposition.py", line 445, in <module>
    DECOM.decomposition()
  File "/SpatialScope/./src/Decomposition.py", line 363, in decomposition
    self.LoadModel()
  File "/SpatialScope/./src/Decomposition.py", line 89, in LoadModel
    model_single = SCGradNN(input_dim1 = self.data.shape[1], down_block_dim=states['down_block_dim'], factors = states['factors']).to(self.config.device)
KeyError: 'factors'

Could you please let me know how to fix the issue.

Thanks,

Chen

**Comment by JiaShun-Xiao** [comment]
Hi, 
thank you for reporting this bug, we have fixed it, please use git pull to update the repository.
By the way, we provide a docker image (docker pull xiaojs95/spatialscope) to avoid installation problems. See the github homepage for more details.
Thanks,
Jiashun

**Comment by JiaShun-Xiao** [comment]
the bug has been fixed

**Comment by ChenJin2020** [comment]
> Hi, thank you for reporting this bug, we have fixed it, please use git pull to update the repository. By the way, we provide a docker image (docker pull xiaojs95/spatialscope) to avoid installation problems. See the github homepage for more details. Thanks, Jiashun

Thank you for fixing the issue and providing the docker image.
